apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-poy0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-poy0@sha256:56a760a5417d494248d08c5ee709c3f3ca850f3c124f9ec570d5228b922fe300
        name: my-nodejs
        resources: {}
status: {}
